version: '3.8'

services:
  client:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SOCKET_SERVER_URL="http://server:3001"

  server:
    build: .
    command: npm run server
    ports:
      - "3001:3001"
    environment:
      - CORS_ORIGIN="http://client:3000"
